environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
os: Visual Studio 2017 # Windows Server 2016
install:
  - java -version
  - mvn --version
  - gradlew.bat --version
build_script:
  - gradlew.bat -u -i install
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
  - mvn clean test
  - gradlew.bat -u -i -S check
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\.m2\ -> pom.xml
